### ISSUE TITLE
如何打造一份优雅的简历 | Stefno

### ISSUE THREAD

**Issue by qcrao** [qcrao/qcrao.github.io#2]
https://qcrao.github.io/2019/07/08/how-to-write-resume-gracefully/ 

 最近一些朋友找我内推，并且给我发了他们的简历。很多简历在我看来都不合格，不只是内容，还有格式，在我这都没过关。然后，我都会把我的简历模板贡献出来，收获了诸多好评。
为了让更多读者朋友拥有一份优雅得体的简历，我会倾其所能，把经验全部传授出来，

**Comment by qcrao** [comment]
这可是我压箱底的，希望能帮到大家~~

**Comment by rongweihe** [comment]
感谢博主的分享~
